name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]
        pip install -r docs_sphinx/requirements.txt
    
    - name: Generate API documentation
      run: |
        python scripts/generate_api_docs.py
    
    - name: Build documentation
      run: |
        cd docs_sphinx
        make html
    
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: documentation
        path: docs_sphinx/_build/html/
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs_sphinx/_build/html/
        force_orphan: true

  linkcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]
        pip install -r docs_sphinx/requirements.txt
    
    - name: Check external links
      run: |
        cd docs_sphinx
        make linkcheck
      continue-on-error: true