name: Documentation (Simple)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'docs_sphinx/**'
      - 'arshai/**'
      - 'scripts/generate_api_docs.py'
      - '.github/workflows/docs-simple.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs_sphinx/requirements.txt
        pip install -e .
    
    - name: Generate API documentation
      run: |
        python scripts/generate_api_docs.py
    
    - name: Build documentation
      run: |
        cd docs_sphinx
        sphinx-build -b html . _build/html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs_sphinx/_build/html
        force_orphan: true